<?php

/**
 * @file
 * Contains snap_stats.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function snap_stats_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the snap_stats module.
    case 'help.page.snap_stats':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom entity type to store analtyics data from Google Analytics') . '</p>';
      return $output;

    default:
  }
}
